### ISSUE TITLE
Unecessary createDatabaseIfNotExist=true

### ISSUE THREAD

**Issue by clementdessoude** [OKaluzny/spring-boot-rest-api-postgresql#1]
Hi @OKaluzny !

I was trying your repo, and I was a bit surprised with this element in the datasource url. I think the `?createDatabaseIfNotExist=true` parameter does not work with Postgres. I would suggest to remove this parameter :)

**Comment by OKaluzny** [comment]
Hi, thanx)
I change it)

Faithfully yours,
Oleg Kaluzny

Viber:    +38 067 981 3142
Skype:   oleg.kaluzny


чт, 5 дек. 2019 г. в 16:12, Clément Dessoude <notifications@github.com>:
